"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import django.core.mail.backends.smtp

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dhpu8zjrss#3s5&8!^8ny6js+&_ry+0d6&r^vkn_fnk6)oe!jz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True	
# DEBUG404 = False


# ALLOWED_HOSTS = ['https://backend-market.tmsiti.uz', 'http://backend-market.tmsiti.uz', 'backend-market.tmsiti.uz', 'www.backend-market.tmsiti.uz', 'localhost', '127.0.0.1']
# ALLOWED_HOSTS = ['http://catalog.tmsiti.uz', 'https://catalog.tmsiti.uz', 'catalog.tmsiti.uz', 'www.catalog.tmsiti.uz', 'https://backend-market.tmsiti.uz', 'http://backend-market.tmsiti.uz', 'backend-market.tmsiti.uz', 'www.backend-market.tmsiti.uz', '127.0.0.1', 'localhost', '109.94.172.135']
ALLOWED_HOSTS = ['*']

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    #'multi_captcha_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    # Manually installed apps
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'axes',
    # 'dj_rest_auth.registration',
    # 'allauth',
    # 'allauth.account',
    'drf_yasg',
    'corsheaders',
    'import_export',
    'django_extensions',
#    'rest_captcha',
    'captcha',
#    'whitenoise.runserver_nostatic',
    # 'rest_framework_swagger',
    # Manually created apps
    'users',
    'app_materials',
    'app_technos',
    'app_products',
    'app_machines_and_mechanisms',
    'app_small_mechanisms',
    'app_works',
    'app_csr',
    'app_api',
    'app_company',
    'app_order',
    'app_cmeta',
]



MULTI_CAPTCHA_ADMIN = {
    'engine': 'simple-captcha',
}

SIMPLE_CAPTCHA = {
    'width': 200,
    'height': 50,
    'font_size': 24,

    'CAPTCHA_TIMEOUT': 600,  # CAPTCHA timeout in seconds
}


##### REST CAPTCHA #########################
REST_CAPTCHA = {
    'CAPTCHA_CACHE': 'default',
    'CAPTCHA_TIMEOUT': 300,  # 5 minutes
    'CAPTCHA_LENGTH': 4,
    'CAPTCHA_FONT_SIZE': 22,
    'CAPTCHA_IMAGE_SIZE': (90, 40),
    'CAPTCHA_LETTER_ROTATION': (-35, 35),
    'CAPTCHA_FOREGROUND_COLOR': '#001100',
    'CAPTCHA_BACKGROUND_COLOR': '#ffffff',
    #'CAPTCHA_FONT_PATH': FONT_PATH,
    'CAPTCHA_CACHE_KEY': 'rest_captcha_{key}.{version}',
    'FILTER_FUNCTION': 'rest_captcha.captcha.filter_default',
    'NOISE_FUNCTION': 'rest_captcha.captcha.noise_default'
}




CACHES={
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rest-captcha',
        'MAX_ENTRIES': 10000,
    }
}



# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':[
        #'rest_framework.permissions.IsAuthenticated',
	'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'apps.core.pagination.StandardResultsSetPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 24,
}

# SWAGGER_SETTINGS = {
#     'docExpansion': 'none',
# }


RECAPTCHA_PUBLIC_KEY = '6LeygDIqAAAAAOne8ejEkMJZwlKqPcTGMRRo7u4v'
RECAPTCHA_PRIVATE_KEY = '6LeygDIqAAAAABEPJ2ehMdrhVa4tuSgYwceFiRDo'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
#    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]


CSRF_TRUSTED_ORIGINS = ['https://backend-market.tmsiti.uz', 'http://10.190.25.113:3003', "http://127.0.0.1:5500"]



AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',  # Asosiy Django authentication backend
]

from datetime import timedelta


AXES_FAILURE_LIMIT = 5  # Urinishlar sonini belgilash
AXES_COOLOFF_TIME = timedelta(minutes=1)



CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    'cache-control',
    'token',
)

# CORS_ALLOW_METHODS = (
#     # "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# )

CORS_ORIGIN_WHITELIST = [
    'https://catalog.tmsiti.uz',
    'http://catalog.tmsiti.uz',
    'https://tmsiti.vercel.app',
    'http://tmsiti.vercel.app',
    'https://localhost:3000',
    'https://localhost:3001',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:5500',
    "https://new-catalog.vercel.app",
]

# CORS_ALLOWED_ORIGINS = [
#     '*',
# ]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tmsitiuz_catalog',
        'USER': 'tmsitiuz',
        'PASSWORD': 'pwd4catalogDB',
        'HOST': 'localhost',
        'PORT': '3306',
	'OPTIONS': {
    		'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    		'charset': 'utf8mb4',
		}
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

# if DEBUG:
# else:

MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/html/catalog/media'
#MEDIA_ROOT = 'media-files'
STATIC_URL = '/static/'
#STATIC_ROOT = '/var/www/html/catalog/static'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_ROOT = '/home/user/backend/Katalog/static-files'
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     # "/home/tmsitiuz/backend-market/static/",
# ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CatalogUsers'

LOGIN_URL = 'rest_framework:login'
LOGOUT_URL = 'rest_framework:logout'

# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'


JAZZMIN_SETTINGS = {
    "site_title": "Elektron katalog",
    "site_header": "Elektron katalog",
    # "site_logo": "https://rcsc.uz/static/img/LOGO4.png",
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'tmsiti.work@gmail.com'
EMAIL_HOST_PASSWORD = 'oamrqyaeilwbgkqr'
EMAIL_PORT = 587

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
